# Generated by Django 5.2.8 on 2025-11-30 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional logo used on dashboard / storefront.', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_name',
            field=models.CharField(help_text='Public name of the business shown on the storefront.', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_email',
            field=models.EmailField(help_text='Primary contact email for this business.', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this profile was first created.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
