# Generated by Django 5.2.8 on 2025-12-02 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_profile_options_profile_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Internal code, e.g. 'trial', 'basic', 'pro'.", max_length=20, unique=True)),
                ('name', models.CharField(help_text='Human friendly name shown to users.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, help_text='Monthly price in GBP (for display / docs).', max_digits=6)),
                ('max_batches', models.PositiveIntegerField(default=0, help_text='Recommended maximum number of batches for this plan.')),
                ('max_cards_per_batch', models.PositiveIntegerField(default=0, help_text='Recommended maximum cards per batch.')),
                ('max_total_cards', models.PositiveIntegerField(default=0, help_text='Recommended total cards across all batches.')),
                ('stripe_price_id', models.CharField(blank=True, help_text='Optional Stripe Price ID for this plan.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls order in admin / pricing list.')),
            ],
            options={
                'ordering': ['sort_order', 'monthly_price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MintKitAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_id', models.CharField(help_text='Internet Identity principal (or external MintKit ID).', max_length=255, unique=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True, help_text='When this mapping was first created.')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time this principal accessed MintKit via the Hub.', null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mintkit_access', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'MintKit access link',
                'verbose_name_plural': 'MintKit access links',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='End of trial or current paid period.', null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.profile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
