# Generated by Django 5.2.8 on 2026-01-05 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mintkitaccess',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_batches',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_cards_per_batch',
        ),
        migrations.AddField(
            model_name='mintkitaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this mapping was first created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mintkitaccess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_featured_cards',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_storefronts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mintkitaccess',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Last time the Studio link was used/confirmed (optional).', null=True),
        ),
        migrations.AlterField(
            model_name='mintkitaccess',
            name='linked_at',
            field=models.DateTimeField(blank=True, help_text='When the Principal ID was first linked.', null=True),
        ),
        migrations.AlterField(
            model_name='mintkitaccess',
            name='principal_id',
            field=models.CharField(blank=True, help_text='Internet Identity Principal ID from MintKit Studio.', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the subscription first started (set when first activated/trialed).', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete')], default='incomplete', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.SlugField(help_text='Short unique code used in URLs and logic (e.g. basic, pro).', unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_total_cards',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited (unless enforced elsewhere).'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly price shown in the UI/admin (e.g. 9.99).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='sort_order',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
