# Generated by Django 5.2.8 on 2026-01-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_cancel_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
