# Generated by Django 5.2.8 on 2025-11-30 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_profile_logo_and_more'),
        ('storefronts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storefront',
            options={'verbose_name': 'Storefront', 'verbose_name_plural': 'Storefronts'},
        ),
        migrations.RemoveField(
            model_name='storefront',
            name='name',
        ),
        migrations.RemoveField(
            model_name='storefront',
            name='owner',
        ),
        migrations.AddField(
            model_name='storefront',
            name='contact_details',
            field=models.TextField(blank=True, help_text='How customers can contact the business (phone, email, links).'),
        ),
        migrations.AddField(
            model_name='storefront',
            name='profile',
            field=models.OneToOneField(blank=True, help_text='The business profile that owns this storefront.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storefront', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this storefront was first created.'),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='description',
            field=models.TextField(blank=True, help_text='Longer description of the business, services, etc.'),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='headline',
            field=models.CharField(help_text='Short headline shown at the top of the storefront page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only active storefronts are publicly visible.'),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='slug',
            field=models.SlugField(help_text='Used in the public URL, e.g. /storefront/<slug>/', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this storefront was last updated.'),
        ),
    ]
