# Generated by Django 5.2.8 on 2025-12-08 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_profile_logo_and_more'),
        ('storefronts', '0002_alter_storefront_options_remove_storefront_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storefront',
            options={},
        ),
        migrations.AddField(
            model_name='storefront',
            name='logo',
            field=models.ImageField(blank=True, help_text='Brand logo shown at the top of your storefront.', null=True, upload_to='storefront_logos/'),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='contact_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='headline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storefront', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
