# Generated by Django 5.2.8 on 2025-12-09 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefronts', '0003_alter_storefront_options_storefront_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('price_label', models.CharField(blank=True, help_text='E.g. £25.00 or From £10', max_length=40)),
                ('image_url', models.URLField(help_text='Paste the thumbnail.webp URL from MintKit.', max_length=500, verbose_name='Card image URL (thumbnail.webp)')),
                ('buy_url', models.URLField(help_text='Link customers should use to buy or view the card.', max_length=500, verbose_name='Buy / details URL')),
                ('description', models.TextField(blank=True, help_text='Short description of what the card includes, expiry rules, etc.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='storefronts.storefront')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
