# Generated by Django 5.2.8 on 2025-12-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefronts', '0004_storefrontcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefront',
            name='business_category',
            field=models.CharField(blank=True, choices=[('beauty_wellness', 'Beauty & wellness'), ('food_drink', 'Food & drink'), ('retail', 'Retail & shops'), ('events_tickets', 'Events & tickets'), ('services', 'Professional services'), ('education', 'Courses & education'), ('sports_fitness', 'Sports & fitness'), ('digital_products', 'Digital products & subscriptions'), ('charity', 'Charities & causes'), ('other', 'Other')], help_text='Used to group storefronts in Explore.', max_length=50),
        ),
        migrations.AddField(
            model_name='storefront',
            name='region',
            field=models.CharField(blank=True, choices=[('online', 'Online / remote'), ('uk', 'UK (all regions)'), ('uk-london', 'UK – London'), ('uk-norfolk', 'UK – Norfolk'), ('eu', 'Europe (general)'), ('eu-france-paris', 'France – Paris'), ('us', 'USA (general)'), ('us-california', 'USA – California'), ('africa', 'Africa'), ('asia', 'Asia'), ('oceania', 'Oceania / Australia'), ('other', 'Other / not listed')], help_text='Where your business mainly operates.', max_length=50),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='is_active',
            field=models.BooleanField(default=False, help_text='If ticked, this storefront can appear in Explore.'),
        ),
    ]
