# Generated by Django 5.2.8 on 2025-12-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefronts', '0005_storefront_business_category_storefront_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefront',
            name='region',
            field=models.CharField(blank=True, choices=[('online', 'Online / remote'), ('uk', 'United Kingdom'), ('eu', 'Europe'), ('us', 'United States'), ('africa', 'Africa'), ('asia', 'Asia'), ('oceania', 'Oceania / Australia'), ('other', 'Other / not listed')], help_text='Where your business mainly operates.', max_length=50),
        ),
    ]
