# Generated by Django 5.2.8 on 2025-12-13 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefronts', '0006_alter_storefront_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('styles', models.JSONField(blank=True, default=dict)),
                ('bg', models.CharField(blank=True, default='#ffffff', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storefront', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout_data', to='storefronts.storefront')),
            ],
        ),
    ]
